#exclude: '^$'
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: detect-private-key
  - repo: git@github.com:gruntwork-io/pre-commit.git
    rev: v0.1.5
    hooks:
      - id: shellcheck
      - id: gofmt
      - id: golint
        exclude: generated/archetype/archetype.go
